### ISSUE TITLE
Función "createNextVoucher()" tiene a CbteDesde y CbteHasta como valores obligatorios en typescript

### ISSUE THREAD

**Issue by ferminc** [ralcorta/afip.ts#20]
Al intentar usar esa función genera el error "Type [...] is missing the following properties from type 'IVoucher': CbteDesde, CbteHasta", obviamente no debería pedirlos a diferencia de createVoucher()

**Comment by ralcorta** [comment]
@ferminc Gracias por comentar el error. Acabo de subir un PR con varios cambios, dentro de esos cambios se encuentra la corrección a este typo!

**Comment by ferminc** [comment]
Fijate que quedó IVoucher como parametro de createNextInvoice() el resto todo de 10!

https://github.com/ralcorta/afip.ts/blob/main/src/services/electronic-billing.service.ts#L263

**Comment by ralcorta** [comment]
@ferminc Gracias por el chequeo, acabo de subir el cambio a la nueva version 👍
