### ISSUE TITLE
handleTicket

### ISSUE THREAD

**Issue by niko-master** [ralcorta/afip.ts#28]
Cuando handleTicket está en true, para poder manejar los tokens de afip y guardarlos en una DB o storage arroja el siguiente error:
"Error: Tokens are not defined yet. Set it when Afip class is instanced."
No entiendo como obtener los tokens de afip y en la documentación parece faltar la parte que explica como hacer login y pasar los tokens a algun servicio luego.

**Comment by ralcorta** [comment]
@niko-master Acabo de subir un PR con muchos cambios al package, dentro de estos se encuentra la corrección a este como también nueva documentación con la explicación de como manejar las credenciales de manera manual: [https://ralcorta.github.io/afip.ts/credential_management.html](https://ralcorta.github.io/afip.ts/credential_management.html)
