### ISSUE TITLE
No existe el SRC en el build

### ISSUE THREAD

**Issue by Murzbul** [ralcorta/afip.ts#5]
**Describe the bug**
Cuando se instala el paquete no existe el contenido del source. Por lo tanto no se puede instalar.

**To Reproduce**
1. pnpm install afip.ts

**Screenshots**
![image](https://user-images.githubusercontent.com/7916055/215469927-c191482b-8d3f-4bda-af4c-f4f3c504285b.png)
![image](https://user-images.githubusercontent.com/7916055/215470034-4d73e0c7-d9e8-4089-a871-4fe48041bd50.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint

**Additional context**

**Comment by Murzbul** [comment]
Te falto agregar lo de SOAP.

![image](https://user-images.githubusercontent.com/7916055/215794065-96d49054-ae40-430b-aced-22480e270b4c.png)
![image](https://user-images.githubusercontent.com/7916055/215794104-2783f4d6-6c4b-4191-8368-268034f0ff52.png)

**Comment by ralcorta** [comment]
Nueva version subida. Ahora tendrian que estar en [NPM](https://www.npmjs.com/package/afip.ts?activeTab=explore) la version con todos los wsdl.

**Comment by Murzbul** [comment]
@ralcorta excelente! Muchas gracias!
