### ISSUE TITLE
ENOENT: no such file or directory, open '/opt/app/node_modules/afip.ts/lib/auth/tickets/TA-X-ws_sr_constancia_inscripcion-production.json'

### ISSUE THREAD

**Issue by jhinmelw3** [ralcorta/afip.ts#68]
Hola, estoy usando la library y estamos teniendo un problema en el ambiente productivo. La primera vez que se consulta, devuelve el error mencionado. Las sucesivas veces posteriores funciona de manera normal. Solo falla en la primer consulta. Aquí, como se está utilizando:
`
async getLegalInfo(cuit: string): Promise<AfipInfo> {

     const afip = new Afip({
         key: process.env.AFIP_LOGIN_CMS_PRIVATE_KEY!,
         cert: process.env.AFIP_LOGIN_CMS_CERTIFICATE_PEM!,
         cuit: Number(process.env.AFIP_CUIT!),
        production: process.env.TEST?.toLowerCase() === 'false',
    });
       const afipInfo =
        await this.getAfip().registerInscriptionProofService.getTaxpayerDetails(
          Number(cuit),
        );
      if (!afipInfo.datosGenerales) throw new AfipException('Invalid CUIT');
      const { datosGenerales, datosRegimenGeneral } = afipInfo;
   //resto del proceso
}
`
El error:
`
Error: ENOENT: no such file or directory, open '/opt/app/node_modules/afip.ts/lib/auth/tickets/TA-20268032992-ws_sr_constancia_inscripcion-production.json'
    at async open (node:internal/fs/promises:636:25)
    at async Object.writeFile (node:internal/fs/promises:1216:14)
`
Node version: 18.18.1

**Comment by ralcorta** [comment]
Hola @jhinmelw3 . No logre replicar el problema, pero agregue un chequeo extra al momento de validar la lectura de los tokens de auth guardados localmente ya que parece ser ahi el problema. 
Cualquier cosa lo volvemos a revisar!

**Comment by jhinmelw3** [comment]
Mil gracias @ralcorta Lo pruebo y si vuelve a fallar les aviso.

**Comment by jhinmelw3** [comment]
Me volvió a pasar el mismo error:
`Error: ENOENT: no such file or directory, open '/opt/app/node_modules/afip.ts/lib/auth/tickets/TA-30716524112-ws_sr_constancia_inscripcion-production.json'
    at async open (node:internal/fs/promises:636:25)
    at async Object.writeFile (node:internal/fs/promises:1216:14)`

Lo raro es que sólo me sucede cuando redeployamos (supongo que se borran los directorios) el sitio y sólo la primera vez que le pegamos. en las sucesivas veces posteriores, ya funciona correctamente (supongo una vez que los directorios ya existen). Cabe aclarar que las pruebas las hice con la versión 3.2.1
